### ISSUE TITLE
Unnecessary command name check

### ISSUE THREAD

**Issue by ExampleWasTaken** [MetalTurtle18/Custom-Heads-Command-Plugin#3]
I've seen this plugin on TechnoVision and you wrote, that you'd appreciate some tips. 
I only found two things you could do better: 
- you don't have to check for the command name. In the main method you specified what command the method should look out for and thus won't fire for anything command than the one you set in the main method.
- don't import everything from Bukkit. This is considered bad practice. Intelli will tell you want you need and give you the possibility to import it.

Other than that, great first plugin! Has potential, and the fact that you worked with a config already is quite surprising too, I think!
Keep up the work! We can never have enough of you!!

**Comment by MetalTurtle18** [comment]
Thanks so much for the feedback! These both sound like good suggestions, I'll fix it as soon as I am able. I am also planning to test a bunch of older versions so I can list them as compatible on the Spigot page.

**Comment by MetalTurtle18** [comment]
As far as your second suggestion, I have fixed it but something weird happened that caused it to be added. I think as soon as I had imported a certain number of things from org.bukkit it just decided to switch to importing everything automatically. Anyway, I manually fixed it.

**Comment by MetalTurtle18** [comment]
Fixed in latest commit. Thanks for the help!
